//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SyncClock.Client.Resources {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SyncClock.Client.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Your clock is approximately {0} seconds ahead..
        /// </summary>
        internal static string AheadClock {
            get {
                return ResourceManager.GetString("AheadClock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a {0}. unsuccessful synchronization done at: {1}..
        /// </summary>
        internal static string FailedSync {
            get {
                return ResourceManager.GetString("FailedSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Invalid sync configuration in syncsettings.json, if you don&apos;t know how to solve it, delete the file..
        /// </summary>
        internal static string InvalidSyncConfiguration {
            get {
                return ResourceManager.GetString("InvalidSyncConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Your clock is approximately {0} seconds late..
        /// </summary>
        internal static string LateClock {
            get {
                return ResourceManager.GetString("LateClock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ---------------------------------
        ///Main Menu (Sync every {0} minutes)
        ///---------------------------------
        ///
        ///   1. Check completed syncs
        ///   2. Check delay
        ///   3. Exit
        ///
        ///Use the ↑ and ↓ arrows to select options, and Enter for the desired option.
        /// </summary>
        internal static string MainBanner {
            get {
                return ResourceManager.GetString("MainBanner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Press any key to continue. . ..
        /// </summary>
        internal static string PressAnyKey {
            get {
                return ResourceManager.GetString("PressAnyKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a {
        ///  &quot;Logging&quot;: {
        ///    &quot;LogLevel&quot;: {
        ///      &quot;Default&quot;: &quot;None&quot;,
        ///      &quot;Microsoft.Hosting.Lifetime&quot;: &quot;None&quot;
        ///    }
        ///  }
        ///}.
        /// </summary>
        internal static string SettingsApp {
            get {
                return ResourceManager.GetString("SettingsApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a {
        ///  &quot;SyncConfiguration&quot;: {
        ///    &quot;NtpServers&quot;: [
        ///      &quot;time.windows.com&quot;,
        ///      &quot;time.nist.gov&quot;,
        ///      &quot;time.google.com&quot;,
        ///      &quot;time.cloudflare.com&quot;
        ///    ],
        ///    &quot;SyncTime&quot;: 3600000
        ///  }
        ///}.
        /// </summary>
        internal static string SettingsSync {
            get {
                return ResourceManager.GetString("SettingsSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a {0}. synchronization done at: {1}..
        /// </summary>
        internal static string SuccessfulSync {
            get {
                return ResourceManager.GetString("SuccessfulSync", resourceCulture);
            }
        }
    }
}
